# Generated by Django 5.2.6 on 2025-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', '⚽ Jersey'), ('boots', '👟 Football Boots'), ('ball', '🥅 Match Ball'), ('training', '🏋️ Training Gear'), ('accessories', '🎯 Football Accessories'), ('collectibles', '🏆 Collectibles'), ('equipment', '⚙️ Equipments')], default='update', max_length=50),
        ),
    ]
