# Generated by Django 5.2.6 on 2025-09-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_product_title_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='news_views',
            new_name='product_views',
        ),
    ]
