# Generated by Django 5.2.6 on 2025-09-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_news_views_product_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('retro', 'Retro'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('match', 'Match'), ('rumor', 'Rumor'), ('analysis', 'Analysis')], default='update', max_length=50),
        ),
    ]
